version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: erp-store
    container_name: erp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - erp-network

  nginx:
    image: nginx:alpine
    container_name: erp-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - erp-network

  db:
    image: mysql:8.0
    container_name: erp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - erp-network

  redis:
    image: redis:alpine
    container_name: erp-redis
    restart: unless-stopped
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 